<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>PAT</title>
</head>

<body>

<h1>FORMS SHOP </h1>

<form method="post" action="">
	Prod Name <input type="text" name="pname" required autofocus> <br><br>
    Prod Price <input type="text" name="pprice" required> <br><br>
    <button type="submit">SAVE</button>
</form>

<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST'){
	include_once("../connectdb.php");
	$pname = $_POST['pname'];
	$pprice =  $_POST['pprice'];
	$sql = "INSERT INTO products (p_name, p_price) VALUES ('{$pname}','{$pprice}')";
	mysqli_query($conn, $sql) or die ('insert error');
	
	echo "<script>";
	echo "alert('SUCCESS');";
	echo "</script>";
	
}
?>
</body>
</html>